USE [master]
GO

/****** Object:  Database [Vidzy]    Script Date: 4/18/2020 7:01:48 PM ******/
CREATE DATABASE [Vidzy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vidzy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Vidzy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Vidzy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Vidzy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Vidzy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Vidzy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Vidzy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Vidzy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Vidzy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Vidzy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Vidzy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Vidzy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Vidzy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Vidzy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Vidzy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Vidzy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Vidzy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Vidzy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Vidzy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Vidzy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Vidzy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Vidzy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Vidzy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Vidzy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Vidzy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Vidzy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Vidzy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Vidzy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Vidzy] SET  MULTI_USER 
GO

ALTER DATABASE [Vidzy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Vidzy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Vidzy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Vidzy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Vidzy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Vidzy] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Vidzy] SET  READ_WRITE 
GO


